version: '3'
services:
  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  main:
    build: .
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    container_name: backend-api
    domainname: gruff-production
    environment:
      REDIS: redis
    ports:
        - "80:80"
